server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuedb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1415926
    driver-Class-Name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  support-methods-arguments: true
  reasonable: true
  params: pageNum=currentPage,pageSize=pageSize
  helper-dialect: mysql
#logging:
#  level:
#    com.example.mapper: debug